# Generated by Django 3.2 on 2021-04-23 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('website', models.URLField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='gender', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('released_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='movieapp/static/images')),
                ('review', models.TextField(max_length=500)),
                ('asin', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('director', models.ManyToManyField(to='movieapp.Director')),
                ('genre', models.ManyToManyField(to='movieapp.Genre')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.studio')),
            ],
        ),
    ]
